# Generated by Django 3.2 on 2021-04-20 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_task_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='tag',
            name='task',
            field=models.ManyToManyField(to='home.Task'),
        ),
    ]
