# Generated by Django 3.2 on 2021-04-20 15:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_tag_task'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='status',
            new_name='active',
        ),
    ]
